version: '3'
services:
  portfolio-site-user-management-services:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
      - "443:443"
    environment:
      # Set any required environment variables here
      - ASPNETCORE_ENVIRONMENT=Development
      # - ConnectionStrings__DefaultConnection=your_connection_string
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    ports:
      - 27017:27017
volumes:
  mongodb_data: